name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v2
    - name: Git semver
      uses: paulhatch/semantic-version@v4.0.3
      id: semver
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}-${increment}"
        short_tags: true
        bump_each_commit: false
    - name: Show current version
      run: |
        echo 'Building version ${{steps.semver.outputs.version}}'        
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Zip artifacts linux
      uses: papeloto/action-zip@v1
      if: contains(matrix.os, 'ubuntu')
      with:
        files: target/release/justlist target/release/search target/release/launcher target/release/git-repo target/release/bookmarks
        dest: 'release_${{matrix.os}}_${{steps.semver.outputs.version}}.zip'
    - name: Zip artifacts windows
      uses: papeloto/action-zip@v1
      if: contains(matrix.os, 'windows')
      with:
        files: target/release/justlist.exe target/release/search.exe target/release/launcher.exe target/release/git-repo.exe target/release/bookmarks.exe
        dest: 'release_${{matrix.os}}_${{steps.semver.outputs.version}}.zip'
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release_${{matrix.os}}
        path: |
          release_${{matrix.os}}_${{steps.semver.outputs.version}}.zip
        if-no-files-found: error
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest_${{matrix.os}}"
        prerelease: true
        title: "Development Build"
        files: |
          release_${{matrix.os}}_${{steps.semver.outputs.version}}.zip